gamma: 0.999
minibatch: 30
episode_steps: 9
episode_to_save: 5000
episode_to_monitor: 100
episodes: 100000
#update_step: 200

load_model: true
path_to_load: "saved_models/a2c051"
path_to_save: "saved_models/a2c052"

# Model
lr: 0.00008
device: cpu

# Env random init
episode_init: begin

# A2C
worker_number: 3