gamma: 0.999
minibatch: 64
episode_steps: 9
episode_to_save: 5000
episode_to_monitor: 50
max_buffer_len: 20000
episodes: 50000
begin_train: 1500
#update_step: 200
copy_step: 15
epsilon_delta: 25000
epsilon_start: 1.05

epsilon_end: 0.01
load_model: true
path_to_load: "ddqn6best"
#path_to_save: "duelingqn_final1"
path_to_save: "dqnf1"

# Model
lr: 0.00003
model: dqnf
device: cpu

# DQN-F

lambda: 0.3
margin: 100