gamma: 0.97
minibatch: 128
episode_steps: 9
episode_to_save: 1000
max_buffer_len: 25000
episodes: 30000
begin_train: 1000
#update_step: 200
copy_step: 5
epsilon_delta: 15000
epsilon_start: 1.0

epsilon_end: 0.01
load_model: false
path_to_load: "ddqn"
path_to_save: "ddqn"
plots_to_save: "plots"